import { api } from '../api/client'
import type { PageProps } from './shared'
import { key, options } from './shared'
import { ActionForm, Section, Badge, Empty, TaskButton } from '../components/ui'
import { date, human } from '../components/format'
export function Emergencies({ data, actor, refresh }: PageProps) {
  const incidents = [...data.emergencies].sort((a, b) => (a.status === b.status ? b.created_at.localeCompare(a.created_at) : a.status === 'active' ? -1 : 1))
  return <><div className="page-intro"><span className="eyebrow">EMERGENCY CENTER</span><h1>Clarity when it matters.</h1><p>Record the incident. Identify the zone. Let deterministic safety policy control access.</p><Badge tone={incidents.some(e => e.status === 'active') ? 'red' : 'mint'}>{incidents.filter(e => e.status === 'active').length} active incidents</Badge></div><Section title="Incident register">{!incidents.length && <Empty>No recorded incidents. No emergency is created automatically.</Empty>}<div className="record-grid">{incidents.map(e => <article className={`incident ${e.status}`} key={e.emergency_id}><div className="row"><span className="incident-icon">{e.emergency_type === 'water_leak' ? '≈' : e.emergency_type === 'elevator_failure' ? '↕' : '!'}</span><Badge tone={e.status === 'active' ? 'red' : ''}>{e.severity} · {e.status}</Badge></div><h3>{human(e.emergency_type)}</h3><p>{e.description}</p><p>{e.affected_zone_ids.map(id => data.catalog.zones.find(z => z.id === id)?.name || id).join(', ')}</p><small>Responders: {e.assigned_responder_ids.map(id => data.catalog.people.find(p => p.id === id)?.name || id).join(', ') || 'Unassigned'}</small><ol className="incident-history">{e.history.map((h, i) => <li key={i}><strong>{human(h.action)}</strong><small>{date(h.at)} · {h.actor_id}</small></li>)}</ol>{e.status === 'active' && <><ActionForm submit="Assign responder" fields={[{ name: 'responder', label: 'Contractor / emergency responder', options: options(data.catalog.people.filter(p => ['contractor', 'emergency_responder'].includes(p.role))) }]} onSubmit={async v => { await api.assign(e.emergency_id, actor, v.responder); await refresh() }} /><TaskButton run={async () => { await api.resolve(e.emergency_id, actor); await refresh() }}>Resolve incident</TaskButton></>}</article>)}</div></Section><Section title="Report an incident" eyebrow="OPERATOR ACTION"><ActionForm submit="Trigger emergency policy" fields={[{ name: 'type', label: 'Incident type', options: ['water_leak', 'elevator_failure', 'fire_alarm', 'security_incident'].map(value => ({ value, label: human(value) })) }, { name: 'severity', label: 'Severity', options: ['low', 'medium', 'high', 'critical'].map(value => ({ value, label: human(value) })) }, { name: 'zone', label: 'Affected zone', options: options(data.catalog.zones) }, { name: 'description', label: 'Description' }]} onSubmit={async v => { await api.emergency({ emergency_id: key(), emergency_type: v.type, severity: v.severity, affected_zone_ids: [v.zone], description: v.description, created_by: actor }); await refresh() }} /><p className="fine">Use Utility Room for a water leak or Machine Room for an elevator failure. This records an incident and changes policy; it is not a physical alarm or evacuation system.</p></Section></>
}
