import { AuthPanel } from '../components/AuthPanel'
import { useState } from 'react'
import { api } from '../api/client'
import type { Device, DeviceStatus, RingDevice } from '../api/types'
import type { PageProps } from './shared'
import { options } from './shared'
import { ActionForm, Badge, Empty, Section, TaskButton } from '../components/ui'
import { human } from '../components/format'
function DeviceCard({ device, props }: { device: Device; props: PageProps }) {
  const [status, setStatus] = useState<DeviceStatus>()
  const { data, actor, refresh } = props
  return <article className="device-card"><div className="row"><span className="device-icon">{device.device_type.includes('elevator') ? '↕' : device.device_type.includes('reader') ? '▣' : device.provider === 'ring' ? '◉' : '⌑'}</span><Badge tone={device.simulated ? '' : 'blue'}>{device.simulated ? 'Simulation' : 'Ring inventory'}</Badge></div><h3>{device.name}</h3><p>{human(device.device_type)} · {device.provider}</p><small>Located in {data.catalog.zones.find(z => z.id === device.zone_id)?.name || device.zone_id}</small><div className="capabilities">{device.capabilities.map(c => <span key={c}>{human(c)}</span>)}</div><TaskButton run={async () => setStatus(await api.deviceStatus(device.id))}>Inspect status & mapping</TaskButton>{status && <div className="device-state"><Badge tone={status.available ? 'mint' : 'amber'}>{status.available ? 'Available' : 'Unavailable'}</Badge><p>Mapped: {status.mapping?.zone_ids.map(id => data.catalog.zones.find(z => z.id === id)?.name || id).join(', ') || 'Not mapped'}</p>{status.state && <p>{['door', 'smart_lock', 'turnstile'].includes(device.device_type) ? `Simulated lock: ${status.state.locked ? 'locked' : 'unlocked'}` : device.device_type.includes('elevator') ? `Cabin floor: ${status.state.current_floor ?? 'unknown'} · Authorized floor: ${status.state.authorized_floor ?? 'none'}` : status.state.route.join(' → ') || 'No active route'}</p>}<small>Snapshot at inspection, not live telemetry.</small></div>}<details><summary>Edit zone mapping</summary><Mapping device={device} zones={data.catalog.zones} save={async ids => { await api.map(device.id, ids, actor); setStatus(await api.deviceStatus(device.id)); await refresh() }} /></details></article>
}
function Mapping({ device, zones, save }: { device: Device; zones: PageProps['data']['catalog']['zones']; save: (ids: string[]) => Promise<void> }) {
  const [selected, setSelected] = useState<string[]>([])
  return <div className="mapping"><p className="fine">Replaces the mapping. Doors protect exactly one zone.</p>{zones.map(z => <label key={z.id}><input type="checkbox" checked={selected.includes(z.id)} onChange={e => setSelected(previous => e.target.checked ? [...previous, z.id] : previous.filter(id => id !== z.id))} />{z.name}</label>)}<TaskButton run={async () => { if (!selected.length) throw new Error('Choose at least one zone.'); await save(selected) }}>Save mapping for {device.name}</TaskButton></div>
}
export function Integrations(props: PageProps) {
  const { data, actor, refresh, setRingEvents } = props
  const [ringDevices, setRingDevices] = useState<RingDevice[]>([])
  const [account, setAccount] = useState('')
  const [discovered, setDiscovered] = useState(false)
  return <><div className="page-intro"><span className="eyebrow">ONE BUILDING. MANY SYSTEMS.</span><h1>Connected by Nodum.</h1><p>Sensing establishes context. Policy decides. Connectors carry out authorized actions.</p></div><section className="ring-panel"><div className="section-heading"><div><span className="ring-word">ring</span><h2>The building’s human entry point.</h2></div><Badge tone="blue">PARTNER API ADAPTER</Badge></div><p>Cameras, doorbells, contact and flood/freeze signals. Ring events never unlock a door directly.</p><div className="notice">{data.integrations.some(i => i.mode === 'ring') ? 'Imported Ring inventory exists. Discover again to inspect the account; inventory is not proof of a current connection.' : 'No imported Ring inventory. Account linking and authenticated session setup are required.'}</div><AuthPanel /><ActionForm submit="Discover Ring devices & events" fields={[{ name: 'account', label: 'Linked Ring account ID', value: account }]} onSubmit={async v => { setAccount(v.account); setDiscovered(false); setRingDevices([]); setRingEvents([]); const [devices, events] = await Promise.all([api.ringDevices(v.account), api.ringEvents(v.account)]); setRingDevices(devices); setRingEvents(events); setDiscovered(true) }} /><p className="fine">Ring discovery requires your signed-in Nodum session. An unavailable account does not disable Nodum.</p>{discovered && !ringDevices.length && <Empty>No devices returned by this Ring account.</Empty>}{ringDevices.map(d => <div className="record" key={d.id}><h3>{d.name || d.id}</h3><ActionForm submit="Import & map device" fields={[{ name: 'zone', label: 'Physical zone', options: options(data.catalog.zones) }]} onSubmit={async v => { await api.importRing(account, d.id, v.zone); await refresh() }} /></div>)}</section><Section title="Building connectors" eyebrow="SOFTWARE SIMULATORS"><div className="connector-grid">{data.integrations.filter(i => i.mode === 'simulated').map(i => <article className="connector" key={i.id}><span className="connector-symbol">{i.kind === 'elevator' ? '↕' : i.kind === 'wayfinding' ? '↗' : i.kind === 'credential_reader' ? '▣' : '⌑'}</span><h3>{human(i.kind)}</h3><Badge>Simulation</Badge><p>{data.devices.filter(d => d.integration_id === i.id).length} devices · {i.enabled ? 'Enabled' : 'Disabled'}</p><TaskButton run={async () => { await api.configure(i.id, !i.enabled, actor); await refresh() }}>{i.enabled ? 'Disable' : 'Enable'} simulator</TaskButton></article>)}</div>{!data.integrations.length && <Empty>No integration inventory loaded.</Empty>}</Section><Section title="Device inventory & zone mapping" eyebrow="HARDWARE-AGNOSTIC FOUNDATION"><div className="record-grid">{data.devices.map(d => <DeviceCard key={d.id} device={d} props={props} />)}</div>{!data.devices.length && <Empty>No devices registered.</Empty>}</Section></>
}
