import { useClock } from '../hooks/useClock'
import type { PageProps } from './shared'
import { BuildingView } from '../components/BuildingView'
import { JourneyPanel } from '../components/JourneyPanel'
import { Badge, Section } from '../components/ui'
export function Overview(props: PageProps) {
  const { data, navigate, unavailable } = props
  const active = data.emergencies.filter(e => e.status === 'active')
  const now = useClock()
  const visitors = data.appointments.filter(a => a.status === 'checked_in' && new Date(a.appointment_time).getTime() + a.access_after_minutes * 60000 > now)
  const contractors = new Set(data.catalog.work_orders.filter(w => w.active).map(w => w.contractor_id))
  return <><div className="hero-heading"><div><div className="eyebrow">BUILDING INTELLIGENCE, IN MOTION</div><h1>A place that knows<br />how to welcome you.</h1><p>Tell Nodum why you are here.<br />The building handles the rest.</p></div><button className="assistant-orb" onClick={() => navigate('AI Assistant')} aria-label="Open Nodum AI assistant"><span>✳</span><small>ASK NODUM ↗</small></button></div><div className="metrics">{[[unavailable.includes('appointments') ? '—' : visitors.length, 'Active business visits', 'Visitors'], [unavailable.includes('catalog') ? '—' : contractors.size, 'Authorized contractors', 'Building'], [unavailable.includes('catalog') ? '—' : data.catalog.businesses.length, 'Businesses', 'Businesses'], [unavailable.includes('emergencies') ? '—' : active.length, 'Active incidents', 'Emergencies']].map(([n, label, page]) => <button key={label} onClick={() => navigate(page as PageProps['navigate'] extends (p: infer P) => void ? P : never)}><strong>{n}</strong><span>{label}</span><i>↗</i></button>)}</div><div className="overview-grid"><Section title="The building, at a glance" eyebrow="SPATIAL OVERVIEW" action={<Badge tone={unavailable.includes('emergencies') ? 'amber' : active.length ? 'amber' : 'mint'}>{unavailable.includes('emergencies') ? 'Incident status unavailable' : active.length ? 'Attention required' : 'No active incidents'}</Badge>}><BuildingView data={data} compact /></Section><div className="stack"><Section title="Connected systems" eyebrow="ORCHESTRATION"><div className="ring-summary"><span className="ring-word">ring</span><Badge>REAL INTEGRATION</Badge><p>{data.integrations.some(i => i.mode === 'ring') ? 'Ring inventory available. Connection is a discovery snapshot.' : 'Account linking required. No live Ring status claimed.'}</p><button onClick={() => navigate('Integrations')}>Manage integrations ↗</button></div><div className="system-list">{data.integrations.filter(i => i.mode !== 'ring').map(i => <div className="row" key={i.id}><span>{i.kind.replaceAll('_', ' ')}</span><Badge tone={i.enabled ? 'mint' : ''}>{i.enabled ? 'Simulation enabled' : 'Disabled'}</Badge></div>)}</div></Section><div className="principle"><span>01 / POLICY FIRST</span><h3>Intelligent assistance.<br />Deterministic decisions.</h3><p>AI understands the request. Building policy decides what is allowed.</p><button onClick={() => navigate('Access')}>Inspect access →</button></div></div></div><JourneyPanel {...props} /><Section title="Recent building activity" action={<button onClick={() => navigate('Activity')}>Full timeline ↗</button>}><p>{data.actuators.length} recorded actuator commands · {data.scans.length} credential events · {data.journeys.length} journeys</p>{[...data.actuators].sort((a, b) => b.at.localeCompare(a.at)).slice(0, 3).map(a => <div className="list-row" key={a.id}><span className="event-dot" /><strong>{a.message}</strong><Badge>Simulation</Badge></div>)}</Section></>
}
